sudo: required

language: c

#env:
#  -dsm=5.2

services:
  - docker
  
before_install:
- docker pull synocommunity/spksrc
- docker run -it -v `pwd`:/spksrc synocommunity/spksrc /bin/bash -c "find /"

script:
- ls