sudo: required

language: c

env:
  -SYNOARCH=evansport
  -SYNOARCH=x64

services:
  - docker
  
before_install:
- docker pull synocommunity/spksrc

script:
- docker run -it -v `pwd`:/spksrc synocommunity/spksrc /bin/bash -c "make setup && cd spk/gogs && make arch-$SYNOARCH"
