sudo: required

language: ruby

services:
  - docker
  
before_install:
- docker pull synocommunity/spksrc
- docker run -d -p 127.0.0.1:80:4567 carlad/sinatra /bin/sh -c "cd /root/sinatra; bundle exec foreman start;"
- docker ps -a
- docker docker run -it -v ~/spksrc:/spksrc synocommunity/spksrc /bin/bash -c "cd ls /"
